modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4.7,)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/${mod_id}/icon.png"
logoBlur=false
description='''
Inspired by the anime Witch Hat Atelier, this mod is all about drawing your own magic. Trace sigils on a canvas to weave cozy, everyday enchantments for your day-to-day life and master powerful spells to defeat the enemies and fouls that stand in your way.

Work in progress — expect new sigils, signs and spells over time.
'''


